learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from user_app import views

urlpatterns = [
    path('',views.index,name= 'index'),
    path('admin/', admin.site.urls),
    path('user_app/',include('user_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

learning_users/user_app/urls.py
from django.urls import path
from user_app import views

app_name = 'user_app'

urlpatterns=[
 path('game/', views.game, name='game'),
 path('accessrecord/',views.accessrecord, name= 'accessrecord'),
  path('register/',views.register,name='register'),
  path('user_login/',views.user_login,name='user_login'),


]

learning_users/user_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # additional

    portfolio_site = models.URLField(blank = True)

    profile_pic = models.ImageField(upload_to = 'profile_pics',blank = True)

    def __str__(self):
        return self.user.username

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length = 264,unique = True)
    def __str__(self):
        return self.top_name
class Webpage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)
    def __str__(self):
        return self.name
class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage,on_delete=models.CASCADE)
    date = models.DateField()
    def __str__(self):
        return str(self.date)

learning_users/user_app/forms.py
from django import forms
from django.contrib.auth.models import User
from user_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User

        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model= UserProfileInfo

        fields = ('portfolio_site','profile_pic')

learning_users/templates/user_app/views.py
from django.shortcuts import render
from user_app.forms import UserForm,UserProfileInfoForm
from django.http import HttpResponse
from first_app.models import Topic,AccessRecord,Webpage

# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'user_app/index.html')

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'user_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'user_app/login.html', {})


# Create your views here.




def project(request):
    return render(request,'user_app/PROJECT.html')


def accrec(request):
    Webpages_list = AccessRecord.objects.order_by('date')
    date_dict={'access_records': Webpages_list}
    return render(request,'user_app/accrec.html',context=date_dict)

learning_users/user_app/views.py
from django.shortcuts import render
from user_app.forms import UserForm,UserProfileInfoForm
from django.http import HttpResponse
from user_app.models import Topic,AccessRecord,Webpage

# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'user_app/index.html')

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'user_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'user_app/login.html', {})


# Create your views here.




def game(request):
    return render(request,'user_app/PROJECT.html')


def accessrecord(request):
    Webpages_list = AccessRecord.objects.order_by('date')
    date_dict={'access_records': Webpages_list}
    return render(request,'user_app/accrec.html',context=date_dict)

learning_users/templates/user_app/accrec.html
<!DOCTYPE html>
{% extends 'user_app/base.html' %}
{% block body-block %}
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Access Record</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
    <style>
      table,td,th{
        border: 2px solid black;
        padding-left : 7px;
        padding-right: 7px;
      }
      .jumbotron{
      margin-left : 117px;
      }

    </style>
    <div class="jumbotron">
  <h1 class="display-4">Access Record</h1>
  <!-- <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p> -->
  <hr class="my-4">
  <p>Here's you're access record:</p>

</div>

    <div class="container">
      {% if accessrecords %}
      <table class="table table-borderless table-dark">
  <thead>
    <tr>
      <th scope="col">Company Name</th>
      <th scope="col">Date Accessed</th>
    </tr>
  </thead>
  {% for access in accessrecords %}
  <tbody>


    <tr>
      <td>{{ access.name }}</td>
      <td>{{ access.date }}</td>
    </tr>
  </tbody>
        {% endfor %}
    </table>
        {% else %}
<p>No Access record Found!</p>

      {% endif %}


    </div>
  </body>
</html>
{% endblock %}

learning_users/templates/user_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>
  <body>

    <style>
    body{
    font-size: 1.3EM;
    background-color: white;
    text-align: center;
    border: 35px solid #2EC486;
    border-top: 0px;
    border-bottom: 0px;
    margin: 10px;

    }
    </style>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Ahmed Raza</a>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_app:game' %}">Game</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_app:accessrecord' %}">AccessRecord</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_app:register' %}">Register</a>
          </li>
     {% if user.is_authenticated %}
     <a class="nav-link" href="{% url 'logout' %}">Log Out</a>

{% else %}

     <a class="nav-link" href="{% url 'user_app:user_login' %}">Login</a>
{% endif %}



        </ul>
      </div>
    </div>
  </nav>

<div class="container">
  {% block body-block %}
  {% endblock %}
</div>
  </body>


<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>


</html>

learning_users/templates/user_app/index.html
{% extends 'user_app/base.html' %}
{% block body-block %}

<div class="jumbotron">
  <h1>Welcome to my web application!</h1>
</div>

{% endblock %}

learning_users/templates/user_app/login.html
{% extends 'user_app/base.html' %}
{% block body-block %}

<div class="jumbotron">

  <h2>Please Enter Your Login Credentials</h2>


<form action="{% url 'user_app:user_login' %}" method="post">
{% csrf_token %}
<label for="username">Username:</label>
<input type="text" name="username" value="" placeholder="Input Your Username here">
<label for="password">Password:</label>

<input type="password" name="password" value="">
<input type="submit" name="" value="Login">





</form>
</div>
{% endblock %}

learning_users/templates/user_app/project.html
<!DOCTYPE html>
{% extends 'user_app/base.html' %}
{% block body-block %}
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Connect Four</title>
    <link rel="stylesheet" href="{% static "css/PROJECT.css" %}"/>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">



  </head>

  <body>

    <style>

    .board button{
      background-color: grey;
      height: 100px;
      width: 100px;
      border : 2px solid black;
    border-radius: 100%;
    margin: 1px;
    }

h1{
  color: red;
}

    </style>
    <div class="container">


<div class="jumbotron">
  <h1 class="display-4"><strong>Welcome to my Connect Four Game!</strong></h1>
  <p class="lead">Connect Four chips in a row either horizontally or vertically!</p>
  <hr class="my-4">
  <p class="h3">Good Luck!</p>



</div>

    </div>

    <div class="container" align ='center' >


    <table class="board">
      <tr>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
      </tr>
      <tr>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
      </tr>
      <tr>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
      </tr>
      <tr>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
      </tr>
      <tr>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
      </tr>
      <tr>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
      </tr>
      <!-- <tr>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
        <td><button type="button"></button></td>
      </tr> -->

    </table>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

    <script src="{% static "js/project.js" %}">

    </script>
  </body>
</html>

{% endblock %}

learning_users/templates/user_app/registration.html
{% extends 'user_app/base.html' %}
{% load static %}
{% block body-block %}

{% if registered %}
<h1>Thank you for registering!</h1>

{% else %}
<div class="container">



<h1>Register Here!</h1>
<h3>Fill out the form:</h3>
<form  enctype="multipart/form-data" method="post">
{% csrf_token %}
{{ user_form.as_p }}
{{ profile_form.as_p }}
<input type="submit" name="" value="Register">
</form>

</div>
{% endif %}
{% endblock %}